# Generated by Django 3.2.4 on 2021-06-25 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0002_remove_player_hand'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='hand',
            field=models.CharField(default='', max_length=14),
        ),
    ]
