# Generated by Django 3.2.4 on 2021-06-25 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0003_player_hand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='hand',
        ),
        migrations.AddField(
            model_name='player',
            name='total_played',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='won',
            field=models.IntegerField(default=0),
        ),
    ]
